swagger: "2.0"
info:
  title: This is my swagger UI Docs
  description: This is my company documentation made by me
  version: 1.0
  contact:
    email: habib.a@xelero.io
    liscence:
      name: Apache 2.0
      url: "http://apache.org"
    servers:
      -url: "http://localhost:4000/"
      description: This is my local server
      -url: "https://xelero.io"
      description: This Ahkili api documentation
      
schemes: [http,https]