swagger: "2.0"
info:
  title: This is my swagger UI Docs
  description: This is my company documentation made by me
  version: 1.0
  contact:
    email: habib.a@xelero.io
    liscence:
      name: Apache 2.0
      url: "http://apache.org"
    servers:
      -url: "http://localhost:4000/"
      description: This is my local server
      -url: "https://xelero.io"
      description: This Ahkili api documentation

schemes: [http,https]

paths:
  /string:
    get:
      summary: Return a String
      description: It is just returning a fake string.
      responses:
        200:
          description: Success
          schema:
            type: string
            example: "A fake string"
        400:
          description: User Error
        500:
          description: Internal Server Error
#Return an Object
  /user:
    get:
      summary: This return a single Object
      description: Returning a object.
      responses:
        200:
          description: Success
          schema:
            type: object